version: '3.7'
services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - '5432:5432'
    volumes:
      - noteify_server:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  noteify_server: